version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "80:8000"
    environment:
      - STOCKFISH_PATH=/usr/bin/stockfish
      - ENVIRONMENT=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 